### ISSUE TITLE
Idempotent?

### ISSUE THREAD

**Issue by j4m3s** [mijndert/ansible-cloudwatch-logs-agent#1]
Looking through the install.yml and cleanup.yml it looks like the role won't be idempotent - the installer script is downloaded, called and cleaned-up on each ansible run.  Is my understanding correct, or have I missed some sugar somewhere?

(thank you for creating the role btw - it's shocking that AWS still don't support the LTS version of Ubuntu 8 months after it was released!)

**Comment by mijndert** [comment]
That is correct. I've never put much time into this because I expect AWS to fix this issue rather sooner than later.
Of course you're free to fork and edit.
