### ISSUE TITLE
Worker processes left running on service stop

### ISSUE THREAD

**Issue by j4m3s** [mijndert/ansible-cloudwatch-logs-agent#2]
I've noticed that on running `service awslogs stop`, the `aws-agent-launcher.sh` process is killed but its child processes (`/var/awslogs/bin/python /var/awslogs/bin/aws logs push ...`) are left running.  Having done some digging, that's because in the systemd service file `KillMode=process`.  That setting tells systemd to only kill the process in the PID file but leaves the others running.

Changing to KillMode=`control-group` (the default) means that the worker processes are killed which is what I think we want.  Can I whether there's a reason to have it set to `KillMode=process` instead?

**Comment by mijndert** [comment]
I have since changed this to include a Process Stop action too. Will push the code soon.
